import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import worker from './worker.mjs';
import {validateWarehouse} from './logic.mjs';
import {invoiceTransition} from './invoice-approval.mjs';
const sample=JSON.parse(readFileSync('sample.json','utf8')).data;
test('invoice review enforces ownership, reviewer roles, document isolation and exactly-once posting',async()=>{
 const env=environment();let revision=0;
 const save=async(path,body,email='owner@example.test')=>{const r=await req(env,path,{...body,expectedRevision:revision},email);assert.equal(r.status,200,JSON.stringify(r.data));revision=r.data.revision;return r;};
 await save('restore',{version:1,data:sample,files:{}});
 for(const [name,role] of [['crew@example.test','field'],['other@example.test','field'],['book@example.test','finance'],['ops@example.test','operations'],['client@example.test','customer']])await save('users',{name,role});
 await save('record',{kind:'tasks',id:'assigned',record:{...sample.tasks[0],owner:'crew@example.test',event:'e1'}});
 const record={...sample.expenses[0],number:'TEST-APPROVAL',net:1000,vat:200,taxRates:'KDV: %20'};
 await save('record',{kind:'partners',id:'partner-test',record:{company:'Synthetic Company',name:'Synthetic Partner',share:60,note:''}});
 assert.equal((await req(env,'record',{kind:'partners',record:{company:'Synthetic Company',name:'Second',share:50,note:''},expectedRevision:revision})).status,400);
 for(const email of ['book@example.test','crew@example.test','ops@example.test','client@example.test']){
  const view=(await req(env,'data',null,email)).data;for(const kind of ['partners','partnerMovements','partnerProfitPools']){
   assert.equal(view.data[kind],undefined);assert.equal(view.schema[kind],undefined);
   assert.equal((await req(env,'record',{kind,record:{},expectedRevision:revision},email)).status,403);
  }
 }
 const before=(await req(env,'data')).data.data.expenses.length;
 assert.equal((await req(env,'invoice-approval',{action:'submit',record:{...record,event:'e2'},expectedRevision:revision},'crew@example.test')).status,403);
 await save('invoice-approval',{action:'submit',record,file:{name:'synthetic.pdf',data:btoa('%PDF-1.4 synthetic')}},'crew@example.test');
 const pending=(await req(env,'data')).data.data.invoiceSubmissions[0],doc=(await req(env,'portal-documents',null,'crew@example.test')).data.rows[0];
 assert.equal((await req(env,'data')).data.data.expenses.length,before);
 assert.equal((await req(env,'data',null,'other@example.test')).data.data.invoiceSubmissions.length,0);
 assert.equal((await req(env,'data',null,'ops@example.test')).data.data.invoiceSubmissions,undefined);
 assert.equal((await req(env,'file/'+doc.id,null,'crew@example.test')).status,200);
 assert.equal((await req(env,'file/'+doc.id,null,'other@example.test')).status,403);
 assert.equal((await req(env,'file/'+doc.id,null,'client@example.test')).status,403);
 assert.equal((await req(env,'record',{kind:'invoiceSubmissions',id:pending.id,record:{...pending,status:'Onaylandı'},expectedRevision:revision})).status,403);
 assert.equal((await req(env,'invoice-approval',{action:'approve',id:pending.id,record,expectedRevision:revision},'crew@example.test')).status,403);
 assert.equal((await req(env,'invoice-approval',{action:'return',id:pending.id,note:'',expectedRevision:revision},'book@example.test')).status,400);
 await save('invoice-approval',{action:'return',id:pending.id,note:'Numarayı teyit edin'},'book@example.test');
 assert.equal((await req(env,'invoice-approval',{action:'submit',id:pending.id,record,expectedRevision:revision},'other@example.test')).status,403);
 await save('invoice-approval',{action:'submit',id:pending.id,record},'crew@example.test');
 await save('invoice-approval',{action:'approve',id:pending.id,record},'book@example.test');
 const final=(await req(env,'data')).data.data;assert.equal(final.expenses.length,before+1);assert.equal(final.invoiceSubmissions[0].reviewer,'book@example.test');assert.equal(final.documents[0].target,'expenses:'+final.invoiceSubmissions[0].expense);
 assert.equal((await req(env,'file/'+doc.id,null,'crew@example.test')).status,200);assert.equal((await req(env,'file/'+doc.id,null,'other@example.test')).status,403);
 assert.equal((await req(env,'invoice-approval',{action:'approve',id:pending.id,record,expectedRevision:revision},'book@example.test')).status,409);
 assert.equal((await req(env,'data')).data.data.expenses.length,before+1);
 const tax={company:'Test',type:'Şahıs işletmesi',year:'2026',revenue:1000,cost:200,additions:0,deductions:0,rate:0,credits:0,withholdingBase:100,withholdingRate:20,note:''};
 await save('record',{kind:'taxScenarios',record:tax},'book@example.test');assert.equal((await req(env,'data',null,'crew@example.test')).data.data.taxScenarios,undefined);
 assert.equal((await req(env,'record',{kind:'taxScenarios',record:{...tax,withholdingRate:101},expectedRevision:revision},'book@example.test')).status,400);
 await save('upload',{target:'dispatches:dis1',name:'delivery.png',data:btoa('synthetic-photo')},'ops@example.test');
 const operational=(await req(env,'operational-documents',null,'ops@example.test')).data.rows;
 assert.equal(operational.length,1);assert.equal(operational[0].target,'dispatches:dis1');
 assert.equal((await req(env,'file/'+operational[0].id,null,'ops@example.test')).status,200);
 assert.equal((await req(env,'file/'+doc.id,null,'ops@example.test')).status,403);
 assert.equal((await req(env,'upload',{target:'expenses:'+final.invoiceSubmissions[0].expense,name:'blocked.png',data:btoa('test'),expectedRevision:revision},'ops@example.test')).status,403);
 await save('record',{kind:'products',id:sample.products[0].id,record:{...sample.products[0],brand:'Synthetic brand',model:'Test model'}});
 assert.equal((await req(env,'data')).data.data.products.find(p=>p.id===sample.products[0].id).brand,'Synthetic brand');
 const pid=sample.products[0].id;
 await save('upload',{target:'products:'+pid,name:'product.png',data:btoa('synthetic-image')},'ops@example.test');
 await save('catalogue-action',{action:'request',product:pid,change:'Ekle / güncelle'},'ops@example.test');
 let cdata=(await req(env,'data')).data.data;const cr=cdata.catalogueRequests[0];assert.equal(cdata.catalogueEntries.length,0);
 assert.equal((await req(env,'catalogue-action',{action:'approve',id:cr.id,expectedRevision:revision},'book@example.test')).status,403);
 assert.equal((await req(env,'record',{kind:'catalogueEntries',record:{},expectedRevision:revision})).status,403);
 await save('catalogue-action',{action:'approve',id:cr.id});cdata=(await req(env,'data')).data.data;assert.equal(cdata.catalogueEntries[0].brand,'Synthetic brand');assert.ok(cdata.catalogueEntries[0].photoIds);assert.equal(cdata.catalogueEntries[0].price,undefined);
 await save('record',{kind:'products',id:pid,record:{...sample.products[0],brand:'Changed'}});assert.equal((await req(env,'data')).data.data.catalogueEntries[0].brand,'Synthetic brand');
 await save('catalogue-action',{action:'request',product:pid,change:'Kaldır'},'ops@example.test');cdata=(await req(env,'data')).data.data;assert.equal(cdata.catalogueEntries[0].status,'Yayında');
 await save('catalogue-action',{action:'approve',id:cdata.catalogueRequests.find(r=>r.status==='Onay bekliyor').id});assert.equal((await req(env,'data')).data.data.catalogueEntries[0].status,'Kaldırıldı');
 env.db.close();
});
function environment(){const db=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')))db.exec(readFileSync('drizzle/'+f,'utf8'));const objects=new Map();return {OWNER_EMAIL:'owner@example.test',DB:{prepare(sql){return {sql,values:[],bind(...values){return {...this,values}}}},async batch(statements){db.exec('BEGIN');try{const results=statements.map(s=>{const p=db.prepare(s.sql);if(/^SELECT/.test(s.sql))return {results:p.all(...s.values),meta:{changes:0}};const r=p.run(...s.values);return {results:[],meta:{changes:Number(r.changes)}};});db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e}}},BUCKET:{async put(k,b){objects.set(k,typeof b==='string'?new TextEncoder().encode(b):b)},async get(k){const b=objects.get(k);return b?{body:b,arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}:null}},db,objects};}
async function req(env,path,body,email='owner@example.test',headers={}){const r=await worker.fetch(new Request('https://example.test/api/'+path,{method:body?'POST':'GET',headers:{'oai-authenticated-user-id':'test-id','oai-authenticated-user-email':email,...(body?{'Origin':'https://example.test','Content-Type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined}),env);return {status:r.status,data:r.headers.get('Content-Type')?.includes('json')?await r.json():new Uint8Array(await r.arrayBuffer())};}
test('shared storage, authentication, role boundaries, conflicts, stock checks and backup restore',async()=>{
 const env=environment();let revision=0;
 assert.equal((await req(env,'data',null,'')).status,401);
 assert.equal((await req(env,'data',null,'outsider@example.test')).status,403);
 const save=async(path,body)=>{const r=await req(env,path,{...body,expectedRevision:revision});assert.equal(r.status,200,JSON.stringify(r.data));revision=r.data.revision;return r;};
 for(const kind of ['events','cards','expenses','payments','receipts','statements','cardPayments','staff','advances','extras','resources','allocations','tasks','operations','warehouses','products','stockMoves','rentals','dispatches','returns','rentalReceipts'])for(const r of sample[kind])await save('record',{kind,id:r.id,record:r});
 assert.equal((await req(env,'data')).data.data.events[0].name,sample.events[0].name);
 assert.equal((await req(env,'record',{kind:'events',record:sample.events[0],expectedRevision:0})).status,409);
 assert.equal((await req(env,'record',{kind:'events',record:sample.events[0],expectedRevision:revision},'owner@example.test',{Origin:'https://attacker.test'})).status,403);
 await save('users',{name:'ops@example.test',role:'operations'});
 const view=(await req(env,'data',null,'ops@example.test')).data;
 assert.equal(view.data.expenses,undefined);assert.equal(view.data.events[0].revenue,undefined);assert.equal(view.data.rentals[0].dailyRate,undefined);
 assert.equal((await req(env,'backup',null,'ops@example.test')).status,403);
 assert.equal((await req(env,'record',{kind:'expenses',record:sample.expenses[0],expectedRevision:revision},'ops@example.test')).status,403);
 assert.equal((await req(env,'record',{kind:'dispatches',record:{...sample.dispatches[0],quantity:999},expectedRevision:revision})).status,400);
 assert.equal((await req(env,'record',{kind:'returns',record:{...sample.returns[0],quantity:999},expectedRevision:revision})).status,400);
 await save('upload',{target:'expenses:'+sample.expenses[0].id,name:'test.pdf',data:btoa('%PDF-1.4 test')});
 const b=(await req(env,'backup')).data;assert.equal(b.data.documents.length,1);assert.equal(Object.keys(b.files).length,1);
 await save('restore',b);const restored=(await req(env,'data')).data;assert.equal(restored.data.events.length,sample.events.length);assert.ok([...env.objects.keys()].some(k=>k.startsWith('backups/')));
 assert.equal((await req(env,'file/'+restored.data.documents[0].id)).status,200);
 assert.equal((await req(env,'export')).status,200);
 await save('users',{name:'ops@example.test',role:'disabled'});assert.equal((await req(env,'data',null,'ops@example.test')).status,403);
 // Two clients reading the same revision: exactly one mutation may win.
 const sameRevision=revision;
 const outcomes=await Promise.all([req(env,'record',{kind:'events',record:sample.events[0],expectedRevision:sameRevision}),req(env,'record',{kind:'events',record:sample.events[0],expectedRevision:sameRevision})]);
 assert.deepEqual(outcomes.map(r=>r.status).sort(),[200,409]);
 env.db.close();
});
test('stock timeline rejects returning equipment before it was dispatched',()=>{const d=structuredClone(sample);d.returns[0].date='2000-01-01T00:00';assert.throws(()=>validateWarehouse(d),/İade/);});
test('quote conversion is atomic, cannot repeat, preserves revisions and isolates customer decisions',async()=>{
 const env=environment();let revision=0;
 const save=async(path,body,email='owner@example.test')=>{const r=await req(env,path,{...body,expectedRevision:revision},email);assert.equal(r.status,200,JSON.stringify(r.data));revision=r.data.revision;return r;};
 await save('restore',{version:1,data:sample,files:{}});
 await save('convert-quote',{id:'quote-demo'});
 const state=(await req(env,'data')).data.data,q=state.quotes.find(r=>r.id==='quote-demo'),e=state.events.find(r=>r.id===q.event);
 assert.equal(e.revenue,24000);assert.equal(e.vat,4800);assert.equal(e.budget,16000);
 assert.equal((await req(env,'convert-quote',{id:q.id,expectedRevision:revision})).status,400);
 assert.equal((await req(env,'record',{kind:'quoteLines',id:'line-demo',record:sample.quoteLines[0],expectedRevision:revision})).status,400);
 await save('revise-quote',{id:q.id});const revised=(await req(env,'data')).data.data.quotes.find(r=>r.revision===2);assert.equal(revised.event,'');assert.equal(revised.status,'Taslak');
 await save('record',{kind:'approvals',id:'a1',record:{event:e.id,title:'Tasarım',version:'v1',email:'customer@example.test',status:'Bekliyor',note:''}});
 await save('users',{name:'customer@example.test',role:'customer'});
 await save('users',{name:'other@example.test',role:'customer'});
 const customer=(await req(env,'data',null,'customer@example.test')).data.data;assert.deepEqual(Object.keys(customer).sort(),['approvals','events']);assert.equal(customer.events[0].revenue,undefined);
 assert.equal((await req(env,'data',null,'other@example.test')).data.data.approvals.length,0);
 assert.equal((await req(env,'portal-action',{id:'a1',status:'Onaylandı',expectedRevision:revision},'other@example.test')).status,404);
 await save('portal-action',{id:'a1',status:'Onaylandı',note:'Uygun'},'customer@example.test');
 assert.equal((await req(env,'portal-action',{id:'a1',status:'Reddedildi',expectedRevision:revision},'customer@example.test')).status,400);
 assert.equal((await req(env,'backup',null,'customer@example.test')).status,403);
 await save('users',{name:'crew@example.test',role:'field'});
 await save('record',{kind:'tasks',id:'crew-task',record:{event:e.id,title:'Kurulum',owner:'crew@example.test',due:'2026-10-20',status:'Bekliyor',priority:'Yüksek'}});
 assert.equal((await req(env,'data',null,'crew@example.test')).data.data.tasks.length,1);
 await save('portal-action',{id:'crew-task',status:'Tamamlandı'},'crew@example.test');
 await save('field-report',{task:'crew-task',title:'Kontrol',note:'Saha kontrol edildi'},'crew@example.test');
 assert.equal((await req(env,'data',null,'crew@example.test')).data.data.fieldReports.length,1);
 env.db.close();
});

test('survey measurements and attached photos persist with access checks',async()=>{
 const env=environment();let revision=0;
 const save=async(path,body)=>{const r=await req(env,path,{...body,expectedRevision:revision});assert.equal(r.status,200,JSON.stringify(r.data));revision=r.data.revision;return r;};
 await save('record',{kind:'events',id:'survey-event',record:sample.events[0]});
 await save('record',{kind:'surveys',id:'survey-1',record:{event:'survey-event',title:'Test area',date:'2026-09-14',width:5,length:4,quantity:2,source:'Yerinde ölçüm',note:'Test note'}});
 await save('upload',{target:'surveys:survey-1',name:'test.png',data:btoa('test-image-bytes')});
 const data=(await req(env,'data')).data.data;assert.equal(data.surveys[0].width*data.surveys[0].length*data.surveys[0].quantity,40);
 assert.equal(data.documents[0].target,'surveys:survey-1');assert.equal((await req(env,'file/'+data.documents[0].id)).status,200);
 assert.equal((await req(env,'file/'+data.documents[0].id,null,'outsider@example.test')).status,403);
 assert.equal((await req(env,'upload',{target:'surveys:missing',name:'test.png',data:btoa('test'),expectedRevision:revision})).status,400);
 env.db.close();
});
