Object.assign(names,{customers:'Müşteri rehberi',opportunities:'İş fırsatları',quotes:'Teklifler / revizyonlar',quoteLines:'Teklif kalemleri',externalRentals:'Dış kiralama',fieldReports:'Saha bildirimleri',approvals:'Müşteri onayları',contractors:'Taşeron hakedişleri',maintenance:'Bakım / arıza kayıtları',investments:'Ekipman yatırımları'});
page='workspace';
const businessMenus=[['workspace','İş merkezi'],['sales','Satış / teklif akışı'],['calendar','Ortak kaynak takvimi'],['field','Mobil saha'],['approvaldesk','Onay merkezi'],['assetdesk','Ürün bul / etiket'],['investmentreport','Ekipman yatırım raporu'],['alerts','Bildirim merkezi'],['history','İşlem geçmişi']];
const businessEventOf=eventOf;eventOf=function(k,r){if(k==='quoteLines')return find('quotes',r.quote)?.event;return businessEventOf(k,r)};
const businessNav=renderNav;renderNav=function(){if(['customer','field'].includes(user.role)){$('#nav').innerHTML='';return}businessNav();for(const [id,title] of businessMenus.filter(([id])=>!(['sales','investmentreport','approvaldesk'].includes(id)&&user.role==='operations')&&!(id==='history'&&user.role!=='admin'))){const b=document.createElement('button');b.textContent=title;b.className=page===id?'active':'';b.onclick=()=>go(id);$('#nav').prepend(b)}};
function go(id){page=id;renderNav();render()}
const bButton=(text,id)=>'<button data-go="'+id+'">'+esc(text)+'</button>';
const quoteTotals=q=>{const ls=rows('quoteLines').filter(r=>r.quote===q.id),round=n=>Math.round(n*100)/100;return {net:round(sum(ls,r=>round(r.quantity*r.days*r.price))),vat:round(sum(ls,r=>round(r.quantity*r.days*r.price*r.vatRate/100))),cost:round(sum(ls,r=>r.quantity*r.days*r.cost))}};
async function businessSave(k,r){if(demo){const index=rows(k).findIndex(v=>v.id===r.id);if(index<0)rows(k).push({...r,id:r.id||crypto.randomUUID()});else rows(k)[index]=r;app()}else{await api('record',{kind:k,id:r.id,record:r});await load()}}
function alerts(){const out=[],add=(date,title,section)=>out.push({date,title,section});for(const r of visible('tasks').filter(r=>r.status!=='Tamamlandı'))add(r.due,'Görev · '+r.title,'tasks');for(const r of visible('operations').filter(r=>!['Tamamlandı','Uygulanmıyor'].includes(r.status)))add(r.due,(r.critical==='Kritik'?'Kritik kontrol · ':'Kontrol · ')+r.title,'operations');for(const r of visible('receipts').filter(r=>r.status==='Planlandı'))add(r.date,'Tahsilat · '+money(r.amount),'receipts');for(const r of visible('rentals').filter(r=>dispatched(r)>returned(r)))add(r.end.slice(0,10),'İade · '+r.customer,'rentalreport');for(const r of visible('externalRentals').filter(r=>r.status==='Teslim alındı'))add(r.end.slice(0,10),'Dış kira iadesi · '+r.description,'externalRentals');for(const r of rows('maintenance').filter(r=>r.status!=='Tamamlandı'))add(r.due,'Bakım · '+r.title,'maintenance');for(const r of visible('approvals').filter(r=>r.status==='Bekliyor'))add('','Onay bekliyor · '+r.title,'approvaldesk');for(const p of rows('products')){const stock=sum(inventory().filter(s=>s.product===p.id),s=>s.good);if(stock<p.minimum)add('','Stok uyarısı · '+p.name+' ('+stock+'/'+p.minimum+')','stockreport')}for(const s of rows('statements')){const remaining=s.amount-statementPaid(s);if(remaining>0)add(s.due,'Ekstre ödemesi · '+label('cards',s.card)+' · '+money(remaining),'cardreport')}return out.sort((a,b)=>a.date.localeCompare(b.date))}
let calendarFrom=today(),calendarTo=today(),fieldOwner='',assetQuery='';
const businessRender=render;render=function(){if(['customer','field'].includes(user.role))return portalView();if(!businessMenus.some(([id])=>id===page)){businessRender();if(page==='quotes')quoteActions();if(page==='contractors')contractorActions();return}
 let html='';
 if(page==='workspace')html='<h2>İş merkezi</h2><p>Müşteriden teslimata, bütün iş akışı.</p>'+cards([['Açık iş fırsatı',rows('opportunities').filter(r=>!['Kazanıldı','Kaybedildi'].includes(r.stage)).length],['Bekleyen müşteri onayı',visible('approvals').filter(r=>r.status==='Bekliyor').length],['Açık saha bildirimi',visible('fieldReports').filter(r=>r.status!=='Çözüldü').length],['Takip edilecek kayıt',alerts().length]])+'<div class="business-grid">'+[['Satış ve teklif',['customers','opportunities','quotes','quoteLines']],['Planlama ve saha',['calendar','opreport','field','externalRentals']],['Depo ve ekipman',['assetdesk','stockreport','rentalreport','maintenance']],['Finans ve kontrol',['contractors','payroll','profit','approvaldesk','alerts','history']]].map(([t,links])=>'<section><h3>'+t+'</h3><div class="actions">'+links.filter(k=>schema[k]||businessMenus.some(([id])=>id===k)&&!(user.role==='operations'&&['sales','approvaldesk','investmentreport'].includes(k))&&!(k==='history'&&user.role!=='admin')||['calendar','opreport','stockreport','rentalreport'].includes(k)||schema.expenses&&['profit','payroll'].includes(k)).map(k=>bButton(names[k]||businessMenus.find(([id])=>id===k)?.[1]||({opreport:'Operasyon hazırlığı',stockreport:'Stok',rentalreport:'İadeler',payroll:'Ücret bakiyeleri',profit:'Kârlılık'})[k],k)).join('')+'</div></section>').join('')+'</div>';
 if(page==='sales')html='<h2>Satış ve teklif akışı</h2><div class="actions">'+['customers','opportunities','quotes','quoteLines'].map(k=>bButton(names[k],k)).join('')+'</div>'+cards(['Yeni','Görüşülüyor','Teklif verildi','Kazanıldı','Kaybedildi'].map(s=>[s,rows('opportunities').filter(r=>r.stage===s).length]))+table(['İş fırsatı','Müşteri','Sorumlu','Aşama','Tahmini net tutar'],rows('opportunities').map(r=>[esc(r.title),esc(label('customers',r.customer)),esc(r.owner),esc(r.stage),money(r.expected)]))+'<section><h3>Teklif özetleri</h3>'+quoteTable()+'</section>';
 if(page==='calendar'){html='<h2>Ortak kaynak takvimi</h2><div class="actions"><label>Başlangıç <input id="cal-from" type="date" value="'+calendarFrom+'"></label><label>Bitiş <input id="cal-to" type="date" value="'+calendarTo+'"></label><button id="cal-apply">Göster</button>'+bButton('Rezervasyon ekle','allocations')+'</div>'+table(['Kaynak','Etkinlik','Başlangıç','Bitiş','Adet','Durum'],visible('allocations').filter(r=>r.start.slice(0,10)<=calendarTo&&r.end.slice(0,10)>=calendarFrom).sort((a,b)=>a.start.localeCompare(b.start)).map(r=>[esc(label('resources',r.resource)),esc(label('events',r.event)),esc(r.start),esc(r.end),r.quantity,esc(r.status)]))+'<h3>Kapasite çakışmaları · tüm tarihler</h3>'+table(['Kaynak','Başlangıç','Bitiş','Talep / kapasite','Etkinlikler','Tür'],conflicts());}
 if(page==='field'){const ts=visible('tasks').filter(r=>!fieldOwner||r.owner.toLocaleLowerCase('tr').includes(fieldOwner.toLocaleLowerCase('tr')));html='<h2>Mobil saha</h2><div class="actions"><label>Sorumlu <input id="field-owner" value="'+esc(fieldOwner)+'" placeholder="İsim veya ekip"></label><button id="field-filter">Filtrele</button>'+bButton('Sorun / fotoğraf kaydı','fieldReports')+'</div><p class="muted">Sorumlu filtresi görünümü daraltır. Yetkili operasyon ekibi ortak görevleri görebilir.</p><div class="business-grid">'+ts.map(r=>'<section><h3>'+esc(r.title)+'</h3><p>'+esc(label('events',r.event))+'</p><p>'+esc(r.owner)+' · '+esc(r.due)+'</p><strong>'+esc(r.status)+'</strong>'+(writable.includes('tasks')?'<div class="actions"><button data-task="'+r.id+'">'+(r.status==='Tamamlandı'?'Yeniden aç':'Tamamlandı işaretle')+'</button></div>':'')+'</section>').join('')+'</div>'+(ts.length?'':'<p>Bu sorumlu için görev bulunamadı.</p>');}
 if(page==='approvaldesk')html='<h2>Müşteri onay merkezi</h2><p>Belge sürümü ve müşteri hesabıyla eşleşen kararlar burada tutulur.</p><div class="actions">'+bButton('Onay kaydı oluştur','approvals')+bButton('Ek iş / revizyon','extras')+'</div>'+table(['Etkinlik','Konu','Sürüm','Müşteri','Karar','Not'],visible('approvals').map(r=>[esc(label('events',r.event)),esc(r.title),esc(r.version),esc(r.email),esc(r.status),esc(r.note)]));
 if(page==='assetdesk'){const ps=rows('products').filter(r=>(r.code+' '+r.name+' '+r.serial).toLocaleLowerCase('tr').includes(assetQuery.toLocaleLowerCase('tr')));html='<h2>Ürün bul / etiket</h2><div class="actions"><label>Ürün kodu / seri / ad <input id="asset-search" value="'+esc(assetQuery)+'"></label><button id="asset-find">Bul</button><button id="asset-scan">Kamerayla QR oku</button></div><video id="scanner" hidden playsinline></video>'+table(['Ürün','Kod','Seri','İşlem'],ps.map(r=>[esc(r.name),esc(r.code),esc(r.serial),'<button data-asset="'+r.id+'">Ürün işlemleri</button>']));}
 if(page==='investmentreport'){html='<h2>Ekipman yatırım raporu</h2><div class="actions">'+bButton('Alım maliyetleri','investments')+bButton('Bakım kayıtları','maintenance')+'</div><p class="muted">Şirket geneli, tüm kayıt tarihleri. Bağımsız faturalanmış net kira − tamamlanan bakım gideri. Vergi, taşıma, personel ve amortisman hariç; net kâr değildir.</p>'+table(['Ürün','Yatırım','Net kira geliri','Tamamlanan bakım','Bakım sonrası gelir','Yatırımı karşılama'],rows('products').map(p=>{const capital=sum(rows('investments').filter(r=>r.product===p.id),r=>r.amount),income=sum(rows('rentals').filter(r=>r.product===p.id&&r.status==='Onaylandı'&&r.billing==='Faturalandı'&&r.incomeMode==='Bağımsız gelir'),rentalNet),cost=sum(rows('maintenance').filter(r=>r.product===p.id&&r.status==='Tamamlandı'),r=>r.cost);return [esc(p.name),money(capital),money(income),money(cost),money(income-cost),capital?Math.round((income-cost)/capital*100)+'%':'Alım tutarı yok']}));}
 if(page==='alerts')html='<h2>Bildirim merkezi</h2><p class="muted">Kayıtlar yenilendiğinde hesaplanır; e-posta veya SMS göndermez. Görev, kontrol, tahsilat ve onay vadelerinin yanında stok uyarı eşiği altına düşen ürünler ve bakiyesi kapanmamış kart ekstreleri de burada listelenir.</p>'+table(['Vade','Takip','Durum','İşlem'],alerts().map(r=>[esc(r.date||'—'),esc(r.title),r.date&&r.date<today()?'<strong class="bad">Gecikti</strong>':'Bekliyor',bButton('Kaydı aç',r.section)]));
 if(page==='history'){html='<h2>İşlem geçmişi</h2><p>Son 200 işlem. Tarih, işlem yapan hesap ve işlem türü.</p><div id="audit-list">Yükleniyor…</div>';}
 $('#content').innerHTML=html;$('#content').querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
 if(page==='history'){if(demo)$('#audit-list').textContent='Açık demoda kalıcı işlem geçmişi tutulmaz.';else api('audit').then(x=>{if(page==='history')$('#audit-list').innerHTML=table(['Tarih','Hesap','İşlem'],x.rows.map(r=>[esc(r.at),esc(r.actor),esc(r.action)]))}).catch(e=>notice(e.message));}
 if($('#cal-apply'))$('#cal-apply').onclick=()=>{if(!$('#cal-from').value||$('#cal-to').value<$('#cal-from').value)return notice('Geçerli tarih aralığı seçin');calendarFrom=$('#cal-from').value;calendarTo=$('#cal-to').value;render()};
 if($('#field-filter'))$('#field-filter').onclick=()=>{fieldOwner=$('#field-owner').value;render()};
 $('#content').querySelectorAll('[data-task]').forEach(b=>b.onclick=async()=>{try{const r=find('tasks',b.dataset.task);await businessSave('tasks',{...r,status:r.status==='Tamamlandı'?'Bekliyor':'Tamamlandı'})}catch(e){notice(e.message)}});
 if($('#asset-find'))$('#asset-find').onclick=()=>{assetQuery=$('#asset-search').value;render()};
 if($('#asset-scan'))$('#asset-scan').onclick=scanAsset;
 $('#content').querySelectorAll('[data-asset]').forEach(b=>b.onclick=()=>assetActions(find('products',b.dataset.asset)));
 if(page==='sales')bindQuoteActions();
};
function quoteTable(){return table(['Teklif','Revizyon','Durum','Net','KDV','Toplam','İşlem'],visible('quotes').map(q=>{const t=quoteTotals(q);return [esc(q.title),q.revision,esc(q.status),money(t.net),money(t.vat),money(t.net+t.vat),'<button data-revise="'+q.id+'">Yeni revizyon</button> <button data-printquote="'+q.id+'">Yazdır / PDF</button> '+(q.event?esc(label('events',q.event)):q.status==='Onaylandı'?'<button data-convert="'+q.id+'">Etkinliğe dönüştür</button>':'')]}))}
function quoteActions(){$('#content').insertAdjacentHTML('beforeend','<section><h3>Teklif toplamları ve işlemler</h3>'+quoteTable()+'</section>');bindQuoteActions()}
function bindQuoteActions(){$('#content').querySelectorAll('[data-revise]').forEach(b=>b.onclick=async()=>{try{if(demo){const q=find('quotes',b.dataset.revise),id=crypto.randomUUID();rows('quotes').push({...q,id,status:'Taslak',event:'',approval:'',revision:Math.max(...rows('quotes').filter(r=>r.opportunity===q.opportunity).map(r=>r.revision))+1});rows('quoteLines').push(...rows('quoteLines').filter(r=>r.quote===q.id).map(r=>({...r,id:crypto.randomUUID(),quote:id})));app()}else{await api('revise-quote',{id:b.dataset.revise});await load()}}catch(e){notice(e.message)}});$('#content').querySelectorAll('[data-printquote]').forEach(b=>b.onclick=()=>printQuote(find('quotes',b.dataset.printquote)));$('#content').querySelectorAll('[data-convert]').forEach(b=>b.onclick=async()=>{try{b.disabled=true;if(demo){const q=find('quotes',b.dataset.convert);if(q.event)throw Error('Teklif zaten dönüştürüldü');const o=find('opportunities',q.opportunity),t=quoteTotals(q);if(!rows('quoteLines').some(r=>r.quote===q.id))throw Error('Teklif kalemi ekleyin');const id=crypto.randomUUID();rows('events').push({id,name:q.title,client:label('customers',o.customer),date:o.date,venue:o.venue,revenue:t.net,vat:t.vat,budget:t.cost});q.event=id;o.stage='Kazanıldı';rows('tasks').push({id:crypto.randomUUID(),event:id,title:'Teklif kapsamını ve ekipman rezervasyonlarını teyit et',owner:o.owner,due:o.date,status:'Bekliyor',priority:'Yüksek'});app()}else{await api('convert-quote',{id:b.dataset.convert});await load()}notice('Etkinlik, bütçe ve hazırlık görevi oluşturuldu. Rezervasyon tarihlerini kaynak takviminde teyit edin.')}catch(e){b.disabled=false;notice(e.message)}})}
function printQuote(q){const t=quoteTotals(q),o=find('opportunities',q.opportunity);const w=window.open('','_blank');if(!w)return notice('Yazdırma için açılır pencereye izin verin');w.document.write('<!doctype html><html lang="tr"><meta charset="utf-8"><title>Teklif</title><body><h1>'+esc(q.title)+'</h1><p>'+esc(label('customers',o.customer))+' · Revizyon '+q.revision+' · Geçerlilik '+esc(q.validUntil)+'</p>'+table(['Kalem','Adet','Gün','Birim net','Net toplam'],rows('quoteLines').filter(r=>r.quote===q.id).map(r=>[esc(r.description),r.quantity,r.days,money(r.price),money(r.quantity*r.days*r.price)]))+'<p>Net '+money(t.net)+' · KDV '+money(t.vat)+' · Toplam '+money(t.net+t.vat)+'</p><p>'+esc(q.terms)+'</p><p>'+esc(q.status)+' · '+esc(q.approval)+'</p></body></html>');w.document.close();w.print()}
function contractorActions(){$('#content').insertAdjacentHTML('beforeend','<section><h3>Hakediş kontrolü</h3><p>Hakediş tutarı kontrol amaçlıdır. Kârlılığa yalnızca bağlı finans gideri girer; aynı işi personel ücretlerine yeniden girmeyin.</p>'+table(['Taşeron','Hakediş','Bağlı gider','Fark'],visible('contractors').map(r=>[esc(r.name),money(r.quantity*r.rate),r.expense?money(find('expenses',r.expense)?.net||0):'Gider bağlantısı eksik',r.expense?money(r.quantity*r.rate-(find('expenses',r.expense)?.net||0)):'—']))+'</section>')}
function assetActions(p){form(p.name,[{key:'action',label:'İşlem',options:[['label','QR etiketi yazdır'],['stockMoves','Depo hareketi'],['dispatches','Kiralama teslimi'],['returns','Kiralama iadesi'],['maintenance','Bakım kaydı']]}],async x=>{if(x.action==='label')return printAssetLabel(p);setTimeout(()=>{edit(x.action);const input=$('#dialog [name=product]');if(input)input.value=p.id},0)})}
async function scanAsset(){if(!('BarcodeDetector' in window))return notice('Bu tarayıcı QR kamera okumasını desteklemiyor. Ürün kodunu arama alanına yazabilir veya USB okuyucu kullanabilirsiniz.');let stream;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});const video=$('#scanner');video.hidden=false;video.srcObject=stream;await video.play();const detector=new BarcodeDetector({formats:['qr_code']});const started=Date.now();while(page==='assetdesk'&&Date.now()-started<30000){const codes=await detector.detect(video);if(codes.length){assetQuery=codes[0].rawValue;render();return}await new Promise(r=>setTimeout(r,300))}notice('Kod bulunamadı. Tekrar deneyin.')}catch(e){notice('Kamera açılamadı: '+e.message)}finally{stream?.getTracks().forEach(t=>t.stop());if($('#scanner'))$('#scanner').hidden=true}}
function printAssetLabel(p){if(typeof qrcode!=='function')throw Error('QR bileşeni yüklenemedi');const qr=qrcode(0,'M');qr.addData(p.code);qr.make();const w=window.open('','_blank');if(!w)throw Error('Etiket için açılır pencereye izin verin');w.document.write('<!doctype html><html><meta charset="utf-8"><title>Ürün etiketi</title><body><h2>'+esc(p.name)+'</h2>'+qr.createSvgTag(5,20)+'<p>'+esc(p.code)+'</p><p>'+esc(p.serial)+'</p></body></html>');w.document.close();w.print()}
function portalView(){const customer=user.role==='customer',k=customer?'approvals':'tasks';$('#content').innerHTML='<h2>'+(customer?'Onayınıza sunulanlar':'Bana atanan görevler')+'</h2><div class="business-grid">'+rows(k).map(r=>'<section><h3>'+esc(r.title)+'</h3><p>'+esc(r.event?label('events',r.event):'Teklif onayı')+'</p><p>'+esc(customer?'Sürüm: '+r.version:r.due)+'</p><strong>'+esc(r.status)+'</strong><p>'+esc(r.note||'')+'</p><div class="actions">'+(customer&&r.status!=='Bekliyor'?'':(customer?[['Onaylandı','Onayla'],['Reddedildi','Reddet']]:[['Tamamlandı','Tamamlandı'],['Bekliyor','Yeniden aç']]).map(([s,t])=>'<button data-portal="'+r.id+'" data-status="'+s+'">'+t+'</button>').join(''))+'</div></section>').join('')+'</div>'+(rows(k).length?'':'<p>Hesabınıza atanmış kayıt bulunmuyor.</p>');$('#content').querySelectorAll('[data-portal]').forEach(b=>b.onclick=()=>form(customer?'Kararı kaydet':'Görevi güncelle',[{key:'note',label:customer?'Karar notu':'Not',required:false}],async x=>{await api('portal-action',{id:b.dataset.portal,status:b.dataset.status,note:x.note});await load()}));}
const basicPortal=portalView;portalView=function(){basicPortal();$('#content').insertAdjacentHTML('beforeend','<section><h3>Belgeler</h3><div id="portal-docs">Yükleniyor…</div></section>');api('portal-documents').then(x=>{if($('#portal-docs'))$('#portal-docs').innerHTML=table(['Bağlı kayıt','Dosya'],x.rows.map(d=>[esc(label(user.role==='customer'?'approvals':'fieldReports',d.target.split(':')[1])),'<a href="/api/file/'+encodeURIComponent(d.id)+'">'+esc(d.name)+'</a>']))}).catch(e=>notice(e.message));if(user.role==='field'){$('#content').insertAdjacentHTML('beforeend','<button id="new-field-report">Sorun bildir</button>'+table(['Bildirim','Durum','Fotoğraf'],rows('fieldReports').map(r=>[esc(r.title),esc(r.status),'<button data-attach="fieldReports:'+r.id+'">Fotoğraf ekle</button>'])));$('#new-field-report').onclick=()=>form('Saha bildirimi',[{key:'task',label:'Görev',options:rows('tasks').map(r=>[r.id,r.title])},{key:'title',label:'Başlık'},{key:'note',label:'Açıklama'}],async x=>{await api('field-report',x);await load()});bindAttachments()}};
function attachFile(target){if(demo)return notice('Açık demoda dosya yüklenmez.');const input=document.createElement('input');input.type='file';input.accept='.pdf,.png,.jpg,.jpeg,.webp';input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>10*1024*1024)throw Error('Dosya en fazla 10 MB olabilir');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});await api('upload',{target,name:file.name,data});await load();notice('Dosya kaydedildi.')}catch(e){notice(e.message)}};input.click()}
function bindAttachments(){$('#content').querySelectorAll('[data-attach]').forEach(b=>b.onclick=()=>attachFile(b.dataset.attach))}
const businessRecords=recordsView;recordsView=function(k){businessRecords(k);if(['fieldReports','approvals'].includes(k)){$('#content').insertAdjacentHTML('beforeend','<section><h3>Fotoğraf / belge ekleri</h3>'+table(['Kayıt','İşlem'],visible(k).map(r=>[esc(r.title),'<button data-attach="'+k+':'+r.id+'">Dosya ekle</button>']))+'</section>');bindAttachments()}};
const fullBusinessNav=renderNav;renderNav=function(){fullBusinessNav();if(['customer','field'].includes(user.role))return;const input=document.createElement('input');input.placeholder='Bölüm ara';input.setAttribute('aria-label','Bölüm ara');input.oninput=()=>$('#nav').querySelectorAll('button').forEach(b=>b.hidden=!b.textContent.toLocaleLowerCase('tr').includes(input.value.toLocaleLowerCase('tr')));$('#nav').prepend(input)};
