uxTitles.reconciliation='Ekstre ve gider mutabakatı';uxGroups.find(g=>g[0]==='Finans')[1].push('reconciliation');
const reconciliationNav=renderNav;renderNav=function(...args){reconciliationNav(...args);if(!schema.statements||!schema.payments)return;const group=[...$('#nav').querySelectorAll('details')].find(d=>d.querySelector('summary')?.textContent==='Finans');if(group&&!group.querySelector('[data-reconciliation]')){const b=document.createElement('button');b.dataset.reconciliation='true';b.textContent=uxTitles.reconciliation;b.onclick=()=>go('reconciliation');group.append(b);}};
const reconciliationRender=render;render=function(...args){if(page==='reconciliation'&&schema.statements)return reconciliationView();return reconciliationRender(...args);};
let reconStatement='',reconFrom='',reconTo='';
function reconciliationView(){
 const statements=rows('statements').slice().sort((a,b)=>b.cutoff.localeCompare(a.cutoff));let s=statements.find(s=>s.id===reconStatement)||statements[0];
 if(s&&reconStatement!==s.id){reconStatement=s.id;reconFrom=s.due.slice(0,7)+'-01';reconTo=s.due.slice(0,7)+'-'+new Date(Number(s.due.slice(0,4)),Number(s.due.slice(5,7)),0).getDate();}
 $('#content').innerHTML='<h2>Ekstre ve gider mutabakatı</h2><p>Ekstre borcu, bankaya yapılan ödeme ve kartla ödenmiş giderleri birlikte kontrol edin. Etkinlik filtresi yerine seçili kartın bütün işleri gösterilir.</p><section><label>Banka ekstresi<select id="recon-statement">'+statements.map(x=>'<option value="'+esc(x.id)+'" '+(x.id===s?.id?'selected':'')+'>'+esc(label('cards',x.card))+' · '+esc(x.cutoff)+'</option>').join('')+'</select></label><div class="fields"><label>Taksit vadesi başlangıcı<input id="recon-from" type="date" value="'+esc(reconFrom)+'"></label><label>Taksit vadesi sonu<input id="recon-to" type="date" value="'+esc(reconTo)+'"></label></div><button id="recon-refresh">Karşılaştır</button></section><div id="recon-results"></div>';
 $('#recon-statement').onchange=e=>{reconStatement='';const next=statements.find(s=>s.id===e.target.value);if(next){reconStatement=next.id;reconFrom=next.due.slice(0,7)+'-01';reconTo=next.due.slice(0,7)+'-'+new Date(Number(next.due.slice(0,4)),Number(next.due.slice(5,7)),0).getDate();}reconciliationView();};
 $('#recon-refresh').onclick=()=>{reconFrom=$('#recon-from').value;reconTo=$('#recon-to').value;reconciliationView();};
 if(!s){$('#recon-results').textContent='Önce Banka ekstreleri bölümüne bir ekstre kaydedin.';return;}
 if(!reconFrom||!reconTo||reconFrom>reconTo){$('#recon-results').textContent='Geçerli bir tarih aralığı seçin.';return;}
 const plan=rows('payments').filter(p=>p.method==='Kredi kartı'&&p.card===s.card).flatMap(p=>installments(p).map(i=>({...i,payment:p,expense:find('expenses',p.expense)}))).filter(i=>i.date>=reconFrom&&i.date<=reconTo).sort((a,b)=>a.date.localeCompare(b.date));
 const total=OsamaFinance.round(sum(plan,i=>i.amount)),difference=OsamaFinance.round(s.amount-total),paidToBank=statementPaid(s);
 const evidence=e=>e?rows('documents').filter(d=>d.target==='expenses:'+e.id):[];
 $('#recon-results').innerHTML=cards([['Banka dönem borcu',money(s.amount)],['Aralıktaki kayıtlı taksitler',money(total)],['İncelenecek fark · ekstre − taksit',money(difference)],['Bu ekstreye bankaya ödenen',money(paidToBank)],['Ekstre kalan borç / fazla ödeme',money(s.amount-paidToBank)],['Belgesi eksik taksit',plan.filter(i=>!evidence(i.expense).length).length]])+'<p><strong>'+(Math.abs(difference)<.01?'Toplamlar eşit; işlem eşleşmesi henüz teyit edilmiş sayılmaz.':'Fark var; devreden borç, faiz, ücret, iade veya kayıtsız işlemleri kontrol edin.')+'</strong></p><p>Varsayılan aralık ekstrenin son ödeme ayıdır. Bankanızdaki taksit vadelerine göre değiştirin. Banka işlem satırları henüz içe aktarılmadığı için bu ekran toplam ve belge kontrolü yapar; otomatik banka teyidi değildir.</p>'+table(['Taksit vadesi / sıra','İş / tedarikçi','Gider belgesi','Taksit tutarı','Gider toplamı','Gidere toplam ödeme','Kontrol'],plan.map(i=>{const e=i.expense,docs=evidence(e),expensePaid=e?paid(e):0;return [esc(i.date)+' · '+i.index+'/'+i.total,e?esc(label('events',e.event))+'<br>'+esc(e.vendor):'Gider bağlantısı eksik',e?esc(e.document)+'<br>'+esc(e.number||'Numara yok'):'—',money(i.amount),e?money(e.net+e.vat):'—',money(expensePaid),!e?'Gideri bağlayın':(expensePaid>e.net+e.vat+.01?'Fazla gider ödemesi · ':'')+(docs.length?docs.map(d=>'<a href="/api/file/'+encodeURIComponent(d.id)+'">'+esc(d.name)+'</a>').join('<br>'):'Dosya eksik')];}))+'<section><h3>Belge durumuna göre bu aralıktaki taksitler</h3>'+cards(['Faturalı','Faturasız','Belge bekleniyor'].map(status=>[status,money(sum(plan.filter(i=>i.expense?.document===status),i=>i.amount))]))+'</section><p>Kart borcunu bankaya ödemek ikinci bir gider değildir. Bu ekran muhasebe tutarlarını değiştirmez.</p>';
}
