let D={},schema={},writable=[],user=null,demo=false,page='home',selected='all';
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(n),sum=(a,f)=>a.reduce((s,x)=>s+f(x),0),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={operations:'Operasyon kontrol kayıtları',events:'Etkinlikler',expenses:'Gider / faturalar',payments:'Tedarikçi ödemeleri',receipts:'Müşteri tahsilatları',cards:'Kart tanımları',statements:'Banka ekstreleri',cardPayments:'Kart borcu ödemeleri',staff:'Personel ücretleri',advances:'Avans / ücret ödemeleri',extras:'Ek işler / iadeler',resources:'Ekipman / ekip / araç',allocations:'Kaynak rezervasyonları',tasks:'Görevler',documents:'Fatura / dekont dosyaları'};
const rows=k=>D[k]||[],find=(k,id)=>rows(k).find(x=>x.id===id),label=(k,id)=>{const r=find(k,id);return r?(r.name||r.customer&&r.customer+' · '+(find('products',r.product)?.name||r.product)||r.vendor&&r.vendor+' · '+r.description||r.title||r.description||r.cutoff&&label('cards',r.card)+' · '+r.cutoff||r.date&&r.date+' · '+money(r.amount)||r.id):'Kayıt bulunamadı'};
function eventOf(k,r){if(k==='events')return r.id;if(r.event)return r.event;if(k==='payments')return find('expenses',r.expense)?.event;if(k==='advances')return find('staff',r.staff)?.event;return null}
const visible=k=>rows(k).filter(r=>selected==='all'||!eventOf(k,r)||eventOf(k,r)===selected);
async function api(path,body){const response=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const x=await response.json();if(!response.ok)throw Error(x.error||'İşlem başarısız');return x}
function notice(s){$('#notice').textContent=s}
async function start(){try{const s=await api('session');if(s.user){user=s.user;demo=false;await load()}else login(s.setup)}catch(e){notice(e.message)}}
function login(setup){$('#nav').innerHTML='';$('#account').innerHTML='';$('.toolbar').hidden=true;$('#content').innerHTML='<section class="login"><h2>'+(setup?'Yerel yönetici hesabınızı oluşturun':'Giriş yapın')+'</h2><p>Kayıtlar bu bilgisayardaki veritabanında saklanır. Parolanızı siz belirleyin. Önce örnek paneli hesap açmadan inceleyebilirsiniz.</p><form id="login"><div class="fields"><label>Kullanıcı adı<input name="name" autocomplete="username" required maxlength="80"></label><label>Parola<input name="password" type="password" autocomplete="'+(setup?'new-password':'current-password')+'" required minlength="10"></label></div><div class="actions"><button class="primary">'+(setup?'Hesabı oluştur':'Giriş yap')+'</button><button type="button" id="demo">Örnek paneli incele</button></div></form></section>';$('#login').onsubmit=async e=>{e.preventDefault();try{await api(setup?'setup':'login',Object.fromEntries(new FormData(e.target)));start()}catch(e){notice(e.message)}};$('#demo').onclick=async()=>{const x=await fetch('/sample.json').then(r=>r.json());D=x.data;schema=x.schema;writable=Object.keys(schema).filter(k=>k!=='documents');user={name:'Örnek kullanım',role:'admin'};demo=true;app()}}
async function load(){const x=await api('data');D=x.data;schema=x.schema;writable=x.write;D.users=x.users;app()}
function app(){notice('');$('.toolbar').hidden=false;$('#account').innerHTML='<span>'+esc(user.name)+' · '+esc({admin:'Yönetici',finance:'Muhasebe',operations:'Operasyon'}[user.role])+'</span><button id="exit">'+(demo?'Hesap / giriş':'Çıkış')+'</button>';$('#exit').onclick=async()=>{if(!demo)await api('logout',{});user=null;demo=false;start()};$('#event').innerHTML='<option value="all">Tüm etkinlikler</option>'+rows('events').map(e=>'<option value="'+e.id+'">'+esc(e.name)+'</option>').join('');$('#event').value=selected;$('#event').onchange=e=>{selected=e.target.value;render()};$('#mode').textContent=demo?'ÖRNEK VERİ · Değişiklikler geçici, yenilemede sıfırlanır.':'Yerel veritabanı · Kayıtlar bilgisayarınızda · TRY';renderNav();render()}
function renderNav(){const menus=[['home','Genel görünüm'],['opreport','Operasyon hazırlığı'],['cash','Nakit akışı'],['vendors','Tedarikçi cari hesap'],['payroll','Personel bakiyeleri'],['profit','Etkinlik kârlılığı'],['cardreport','Kart / taksit takibi'],['conflicts','Kaynak çakışmaları'],...Object.entries(names),['backup','Yedek / Excel'],['users','Kullanıcı yetkileri']].filter(([k])=>schema[k]||(['home','conflicts','backup'].includes(k)||(k==='opreport'&&schema.operations))||(['cash','vendors','profit','cardreport','payroll'].includes(k)&&schema.expenses)||(k==='users'&&user.role==='admin'));$('#nav').innerHTML=menus.map(([id,n])=>'<button data-page="'+id+'" class="'+(page===id?'active':'')+'">'+n+'</button>').join('');$('#nav').querySelectorAll('button').forEach(b=>b.onclick=()=>{page=b.dataset.page;renderNav();render()})}
function table(head,body){return body.length?'<div class="scroll"><table><thead><tr>'+head.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+body.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>':'<p class="muted">Bu seçimde kayıt yok.</p>'}
const cards=items=>'<div class="cards">'+items.map(([k,v])=>'<div class="card"><small>'+esc(k)+'</small><strong>'+v+'</strong></div>').join('')+'</div>';
function paid(expense){return sum(rows('payments').filter(p=>p.expense===expense.id),p=>p.amount)}
function wages(s){return s.days*s.rate}function staffPaid(s){return sum(rows('advances').filter(a=>a.staff===s.id),a=>a.amount)}
function statementPaid(s){return sum(rows('cardPayments').filter(p=>p.statement===s.id),p=>p.amount)}
function totals(e){const ex=rows('extras').filter(x=>x.event===e.id&&x.status==='Onaylandı'),revenue=e.revenue+sum(ex,x=>(x.kind==='Müşteri iadesi'?-1:1)*x.amount),expenses=rows('expenses').filter(x=>x.event===e.id),personnel=rows('staff').filter(x=>x.event===e.id),cost=sum(expenses,x=>x.net)+sum(personnel,wages);return {revenue,cost,profit:revenue-cost,unknown:expenses.some(x=>x.document!=='Faturalı')}}
function installments(p){const cents=Math.round(p.amount*100),n=p.installments,b=Math.floor(cents/n);return Array.from({length:n},(_,i)=>{const [y,m,d]=p.firstDue.split('-').map(Number);const dt=new Date(y,m-1+i,1);const max=new Date(dt.getFullYear(),dt.getMonth()+1,0).getDate();dt.setDate(Math.min(d,max));return {date:dt.getFullYear()+'-'+String(dt.getMonth()+1).padStart(2,'0')+'-'+String(dt.getDate()).padStart(2,'0'),amount:(b+(i<cents%n?1:0))/100,card:p.card,index:i+1,total:n}})}
function conflicts(){const out=[];for(const resource of rows('resources')){const bookings=rows('allocations').filter(a=>a.resource===resource.id),times=[...new Set(bookings.flatMap(a=>[Date.parse(a.start+'+03:00'),Date.parse(a.end+'+03:00')+a.buffer*60000]))].sort((a,b)=>a-b);for(let i=0;i<times.length-1;i++){const active=bookings.filter(a=>Date.parse(a.start+'+03:00')<=times[i]&&Date.parse(a.end+'+03:00')+a.buffer*60000>times[i]),q=sum(active,a=>a.quantity);if(q>resource.capacity&&(selected==='all'||active.some(a=>a.event===selected)))out.push([esc(resource.name),esc(new Date(times[i]).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'})),esc(new Date(times[i+1]).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'})),q+' / '+resource.capacity,esc(active.map(a=>label('events',a.event)).join(', ')),active.some(a=>a.status==='Geçici')?'Geçici rezervasyon riski':'Kesin çakışma'])}}return out}
function render(){let html='';const ev=visible('events');
if(schema[page])return recordsView(page);
if(page==='opreport'){const all=visible('operations'),applicable=all.filter(r=>r.status!=='Uygulanmıyor'),done=applicable.filter(r=>r.status==='Tamamlandı'),critical=applicable.filter(r=>r.critical==='Kritik'&&r.status!=='Tamamlandı'),late=applicable.filter(r=>r.due<today()&&r.status!=='Tamamlandı');html='<h2>Operasyon hazırlığı</h2><p class="muted">Hazırlık oranı tamamlanan kontrol sayısı / uygulanabilir kontrol sayısıdır. Kritik eksikler ayrı gösterilir. Yüksek oran tek başına etkinliğin hazır veya güvenli olduğunu göstermez.</p>'+cards([['Hazırlık oranı',applicable.length?Math.round(done.length/applicable.length*100)+'%':'—'],['Kritik açık kontrol',critical.length],['Geciken kontrol',late.length],['Teyit bekleyen',all.filter(r=>r.status==='Teyit bekliyor').length]])+table(['Başlık','Tamamlanan / toplam','Kritik açık'],[...new Set(all.map(r=>r.phase))].map(p=>{const a=applicable.filter(r=>r.phase===p);return [esc(p),a.filter(r=>r.status==='Tamamlandı').length+' / '+a.length,a.filter(r=>r.critical==='Kritik'&&r.status!=='Tamamlandı').length]}))+'<section style="margin-top:20px"><h3>Öncelikle çözülmesi gerekenler</h3>'+table(['Etkinlik','Başlık / kontrol','Sorumlu','Vade','Durum'],critical.map(r=>[esc(label('events',r.event)),esc(r.phase+' · '+r.title),esc(r.owner),esc(r.due),esc(r.status)]))+'</section><p class="muted">Kontrolleri düzenlemek veya eklemek için Operasyon kontrol kayıtları bölümünü kullanın. Tamamlandı durumunda teyit notu veya belge referansı zorunludur.</p>'}
if(page==='home'){const tasks=visible('tasks'),complete=tasks.filter(t=>t.status==='Tamamlandı').length;html='<h2>Genel görünüm</h2>'+cards([['Etkinlik',ev.length],['Açık görev',tasks.length-complete],['Kaynak çakışma aralığı',conflicts().length],...(schema.expenses?[['Belgesi eksik gider',visible('expenses').filter(e=>e.document!=='Faturalı').length]]:[])])+ '<section><h3>Etkinlikler</h3>'+table(['Etkinlik','Tarih','Mekân','Müşteri'],ev.map(e=>[esc(e.name),esc(e.date),esc(e.venue),esc(e.client)]))+'</section><section><h3>İş tamamlama</h3><p>'+complete+' / '+tasks.length+' görev tamamlandı</p><div class="progress"><i style="width:'+(tasks.length?complete/tasks.length*100:0)+'%"></i></div></section>'}
if(page==='vendors'){const expenses=visible('expenses'),vs=[...new Set(expenses.map(e=>e.vendor))];html='<h2>Tedarikçi cari hesap</h2><p class="muted">KDV dahil gider borcu − kayıtlı tedarikçi ödemeleri. Kartla ödeme tedarikçiyi kapatır; kart borcu ayrı takip edilir. Negatif bakiye fazla ödeme/alacaktır.</p>'+table(['Tedarikçi','Toplam borç','Ödenen','Kalan','Vadesi geçmiş'],vs.map(v=>{const r=expenses.filter(e=>e.vendor===v),total=sum(r,e=>e.net+e.vat),p=sum(r,paid);return[esc(v),money(total),money(p),money(total-p),money(sum(r.filter(e=>e.due<today()),e=>Math.max(0,e.net+e.vat-paid(e))))]}))}
if(page==='payroll'){html='<h2>Personel ücret ve avans bakiyeleri</h2><p class="muted">Çalışma günü × günlük ücret − verilen avans/ücret ödemesi. Bordro, vergi ve sigorta hesabı değildir.</p>'+table(['Personel','Etkinlik','Hak edilen','Ödenen','Kalan','Vade'],visible('staff').map(s=>[esc(s.name),esc(label('events',s.event)),money(wages(s)),money(staffPaid(s)),money(wages(s)-staffPaid(s)),esc(s.due)]))}
if(page==='profit'){html='<h2>Etkinlik kârlılığı</h2><p class="muted">Net sözleşme + onaylı ek işler − onaylı müşteri iadeleri − kayıtlı net giderler − personel ücretleri. Avanslar ve kart borcu ödemeleri yeniden gider sayılmaz. Genel merkez giderleri ve vergiler hariç; kayıtlar eksikse sonuç geçicidir.</p>'+table(['Etkinlik','Net gelir','Net maliyet','Kâr / zarar','Bütçe farkı','Belge kontrolü'],ev.map(e=>{const t=totals(e);return[esc(e.name),money(t.revenue),money(t.cost),'<b class="'+(t.profit<0?'bad':'good')+'">'+money(t.profit)+'</b>',money(e.budget-t.cost),t.unknown?'Eksik belge · net tutarı teyit edin':'Kayıtlı belgeler faturalı']}))}
if(page==='cash'){const lines=[];visible('receipts').filter(r=>r.status==='Planlandı').forEach(r=>lines.push([r.date,'Tahsilat · '+label('events',r.event),r.amount,0]));visible('expenses').forEach(e=>{const remaining=e.net+e.vat-paid(e);if(remaining>0)lines.push([e.due,'Tedarikçi · '+e.vendor,0,remaining])});visible('staff').forEach(s=>{if(wages(s)>staffPaid(s))lines.push([s.due,'Personel · '+s.name,0,wages(s)-staffPaid(s)])});rows('cards').map(c=>rows('statements').filter(s=>s.card===c.id).sort((a,b)=>b.cutoff.localeCompare(a.cutoff))[0]).filter(Boolean).forEach(s=>{const rest=s.amount-statementPaid(s);if(rest>0)lines.push([s.due,'Ekstre (şirket geneli) · '+label('cards',s.card),0,rest])});html='<h2>Nakit akış takvimi</h2><p class="muted">Açık müşteri planları, ödenmemiş tedarikçi/personel tutarları ve açık banka ekstreleri. Kartlar şirket genelidir; etkinlik filtresinden bağımsızdır. Devreden borcu çift saymamak için her kartın en son ekstresi kullanılır; önceki dönemle mutabakat gereklidir. Gelecek ekstreye henüz yansımayan taksitler burada dahil değil. Açılış kasa/banka bakiyesi olmadan nakit yeterliliği hesaplanmaz.</p>'+cards([['Planlanan giriş',money(sum(lines,x=>x[2]))],['Planlanan çıkış',money(sum(lines,x=>x[3]))],['Net plan farkı',money(sum(lines,x=>x[2]-x[3]))]])+table(['Vade','Açıklama','Giriş','Çıkış','Durum'],lines.sort((a,b)=>a[0].localeCompare(b[0])).map(x=>[esc(x[0]),esc(x[1]),money(x[2]),money(x[3]),x[0]<today()?'<span class="bad">Vadesi geçti</span>':'Plan']))+'<p class="muted">Müşteri iadesi nakit çıkışı planını ayrıca kaydetmek gerekir; ek iş/iade kaydı tek başına para hareketi değildir.</p>'}
if(page==='cardreport'){const plan=visible('payments').filter(p=>p.method==='Kredi kartı').flatMap(installments);html='<h2>Kart / ekstre takibi</h2><p class="muted">Ekstre borcu banka belgesinden girilir. Taksit planı bilgilendirme içindir; ekstre borcuna eklenmez. Kullanılabilir limit bankadan alınmadığı için hesaplanmıyor.</p>'+table(['Kart','Kesim','Son ödeme','Ekstre borcu','Bankaya ödenen','Kalan'],rows('statements').map(s=>[esc(label('cards',s.card)),esc(s.cutoff),esc(s.due),money(s.amount),money(statementPaid(s)),money(s.amount-statementPaid(s))]))+'<section style="margin-top:20px"><h3>Taksit planı · seçili etkinlik</h3>'+table(['Vade','Kart','Taksit','Tutar'],plan.sort((a,b)=>a.date.localeCompare(b.date)).map(p=>[p.date,esc(label('cards',p.card)),p.index+'/'+p.total,money(p.amount)]))+'</section><p class="muted">Ardışık ekstrelerde önceki dönem devreden borç varsa aynı borcu iki kez toplamamak için eski dönem kaydını mutabık kapatın. Bu görünüm dönemleri ayrı gösterir.</p>'}
if(page==='conflicts')html='<h2>Kaynak çakışmaları</h2><p class="muted">Başlangıç dahil, bitiş hariçtir. Bitişe seyahat/hazırlık tamponu eklenir. Kapasite kontrolü tüm etkinliklerde aynı anda ayrılan toplam adede göre yapılır.</p>'+table(['Kaynak','Başlangıç','Bitiş','Talep / kapasite','Etkinlikler','Tür'],conflicts());
if(page==='backup'){html='<h2>Yedekleme / Excel</h2><section><h3>Kayıtları dışarı alın</h3><p>Excel uyumlu CSV tabloları ZIP dosyasında; tam yedek JSON içinde belgeleri de kapsar. Kullanıcı parolaları dışa aktarılmaz.</p><div class="actions"><button id="csv">Excel tablolarını indir</button>'+(user.role==='admin'?'<button id="backup">Tam yedek indir</button><button id="restore">Yedekten geri yükle</button>':'')+'</div><p class="muted">Geri yüklemeden önce mevcut veritabanının otomatik kopyası alınır. Paylaşımlı ağ erişimi açık değildir; uygulama yalnızca bu bilgisayarda çalışır.</p></section>'}
if(page==='users')html='<h2>Kullanıcılar ve yetkiler</h2>'+table(['Kullanıcı','Rol'],(D.users||[]).map(u=>[esc(u.name),esc(u.role)]))+'<div class="actions"><button id="add-user">Kullanıcı ekle</button></div><section><p><b>Yönetici:</b> Tüm kayıtlar, yedek geri yükleme ve kullanıcı oluşturma.</p><p><b>Muhasebe:</b> Finans, personel, belgeler ve etkinlikler; kullanıcı yönetimi yok.</p><p><b>Operasyon:</b> Etkinliklerin finans dışı bilgileri, görevler, kaynaklar ve rezervasyonlar. Finans verileri sunucudan gönderilmez.</p></section>';
$('#content').innerHTML=html;bindSpecial();}
function today(){return new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Istanbul'})}
function recordsView(k){const fields=schema[k],rs=visible(k);$('#content').innerHTML='<h2>'+names[k]+'</h2><p class="muted">'+(k==='expenses'?'Personel ücretleri ayrı bölümde hesaplanır; burada tekrar girmeyin. Faturasız kayıtta net/KDV tutarı teyit edilmemişse kârlılık geçicidir.':k==='receipts'?'Plan kaydını tahsil edildiye çevirin; aynı ödeme için ikinci kayıt açmayın.':k==='documents'?'PDF, PNG, JPEG veya WebP · dosya başına en fazla 10 MB.':'Kayıt ekleyebilir veya mevcut kaydı düzenleyebilirsiniz.')+'</p><div class="actions">'+(writable.includes(k)&&k!=='documents'?'<button class="primary" id="add-record">+ Yeni kayıt</button>':'')+(k==='documents'?'<button id="upload">Belge ekle</button>':'')+'</div>'+table([...fields.map(f=>f[1]),'İşlem'],rs.map(r=>[...fields.map(([key,_,t])=>t.includes('ref:')?esc(r[key]?label(t.split(':')[1],r[key]):'—'):t==='money'?money(r[key]):esc(r[key])),k==='documents'?'<a href="/api/file/'+r.id+'">İndir</a>':writable.includes(k)?'<button data-edit="'+r.id+'">Düzenle</button>':'Salt okunur']));if($('#add-record'))$('#add-record').onclick=()=>edit(k);$('#content').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(k,find(k,b.dataset.edit)));if($('#upload'))$('#upload').onclick=upload}
function form(title,fields,save){const dlg=$('#dialog');dlg.innerHTML='<form><h2>'+esc(title)+'</h2><div class="fields"></div><p class="error" role="alert"></p><div class="actions"><button class="primary">Kaydet</button><button type="button" id="cancel">Vazgeç</button></div></form>';for(const f of fields){const l=document.createElement('label');l.textContent=f.label;const input=document.createElement(f.options?'select':'input');input.name=f.key;input.required=f.required!==false;if(f.options)f.options.forEach(([v,t])=>input.add(new Option(t,v)));else{input.type=f.type||'text';if(input.type==='number'){input.min=0;input.step='0.01'}input.maxLength=500}if(f.value!==undefined)input.value=f.value;l.append(input);dlg.querySelector('.fields').append(l)}dlg.querySelector('#cancel').onclick=()=>dlg.close();dlg.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await save(Object.fromEntries(new FormData(e.target)));dlg.close()}catch(e){dlg.querySelector('.error').textContent=e.message}};dlg.showModal()}
function edit(k,r){form(names[k],schema[k].map(([key,label,t])=>({key,label,value:r?.[key]??(t==='integer'?1:t==='money'||t==='nonnegative'?0:undefined),required:!t.startsWith('opt') ,type:t==='money'||t==='integer'||t==='nonnegative'?'number':t==='date'||t==='optionaldate'?'date':t==='datetime'?'datetime-local':'text',options:t.startsWith('enum:')?t.slice(5).split(',').map(v=>[v,v]):t.includes('ref:')?[...(t.startsWith('opt')?[['','—']]:[]),...rows(t.split(':')[1]).map(x=>[x.id,labelRef(t.split(':')[1],x.id)])]:undefined})),async record=>{schema[k].forEach(([key,_,t])=>{if(['money','integer','nonnegative'].includes(t))record[key]=Number(record[key])});if(demo){rows(k).splice(r?rows(k).indexOf(r):rows(k).length,r?1:0,{...record,id:r?.id||crypto.randomUUID()});app()}else{await api('record',{kind:k,id:r?.id,record});await load()}})}
const labelRef=(k,id)=>label(k,id);
function bindSpecial(){if($('#csv'))$('#csv').onclick=()=>demo?notice('Örnek modda dışa aktarım kapalı. Kalıcı kayıt için giriş yapın.'):location.assign('/api/export');if($('#backup'))$('#backup').onclick=()=>demo?notice('Örnek modda yedek alınmaz. Kalıcı kayıt için giriş yapın.'):location.assign('/api/backup');if($('#restore'))$('#restore').onclick=()=>{if(demo)return notice('Geri yükleme için yönetici girişi gerekli.');const f=document.createElement('input');f.type='file';f.accept='.json';f.onchange=async()=>{try{const x=JSON.parse(await f.files[0].text());if(!confirm('Yedekteki kayıtlar mevcut kayıtların yerini alacak. Önce mevcut veritabanının kopyası alınacak. Geri yüklensin mi?'))return;await api('restore',x);await load();notice('Yedek geri yüklendi.')}catch(e){notice(e.message)}};f.click()};if($('#add-user'))$('#add-user').onclick=()=>{if(demo)return notice('Kullanıcı oluşturmak için yönetici hesabıyla giriş yapın.');form('Kullanıcı ekle',[{key:'name',label:'Kullanıcı adı'},{key:'password',label:'Parola · en az 10 karakter',type:'password'},{key:'role',label:'Rol',options:[['operations','Operasyon'],['finance','Muhasebe'],['admin','Yönetici']]}],async x=>{await api('users',x);await load()})}}
function upload(){if(demo)return notice('Belge yüklemek için giriş yapın.');const targets=['expenses','payments','receipts','statements','cardPayments'].flatMap(k=>rows(k).map(r=>[k+':'+r.id,names[k]+' · '+label(k,r.id)]));if(!targets.length)return notice('Önce belgeyi bağlayacağınız gider veya ödeme kaydını ekleyin.');form('Belgeyi bağla',[{key:'target',label:'Bağlı kayıt',options:targets},{key:'file',label:'PDF veya görsel',type:'file'}],async x=>{const file=$('#dialog input[type=file]').files[0];if(file.size>10*1024*1024)throw Error('Dosya en fazla 10 MB olabilir');const encoded=await new Promise((res,rej)=>{const reader=new FileReader();reader.onload=()=>res(reader.result.split(',')[1]);reader.onerror=rej;reader.readAsDataURL(file)});await api('upload',{target:x.target,name:file.name,data:encoded});await load()})}
