names.invoiceSubmissions='Muhasebe onayları';uxTitles.invoiceSubmissions=names.invoiceSubmissions;
uxGroups.find(g=>g[0]==='Finans')[1].unshift('invoiceSubmissions');
const beforeApprovalRender=render;
render=function(...args){if(page==='invoiceSubmissions'&&schema.invoiceSubmissions)return invoiceApprovalView();return beforeApprovalRender(...args);};
const beforeApprovalPortal=portalView;
portalView=function(){beforeApprovalPortal();if(user.role!=='field')return;const section=document.createElement('section');section.innerHTML='<h3>Fatura / gider girişlerim</h3><p>Girişi tamamlayıp onaya gönderin. Yönetici veya muhasebe onaylamadan gider oluşmaz.</p><button class="primary" id="field-invoice">+ Fatura / gider gir</button><button id="field-invoice-status">Onay durumlarını gör</button>';$('#content').prepend(section);$('#field-invoice').onclick=()=>invoiceEntry();$('#field-invoice-status').onclick=()=>go('invoiceSubmissions');};
function invoiceApprovalView(){const review=['admin','finance'].includes(user.role),rs=visible('invoiceSubmissions');$('#content').innerHTML='<div class="page-heading"><div><h2>Muhasebe onayları</h2><p>Onay bekleyen kayıtlar gider ve kâr hesaplarına dahil değildir.</p></div><button class="primary" id="approval-new">+ Fatura / gider gir</button></div>'+cards([['Onay bekleyen',rs.filter(r=>r.status==='Onay bekliyor').length],['Düzeltme bekleyen',rs.filter(r=>r.status==='Düzeltme istendi').length],['Onaylanan',rs.filter(r=>r.status==='Onaylandı').length]])+table(['İş / tedarikçi','Tutar / oranlar','Gönderen','Durum','Karar','Belgeler','İşlem'],rs.map(r=>[esc(label('events',r.event))+'<br>'+esc(r.vendor),money(r.net+r.vat)+'<br>'+esc(r.taxRates||'Oran girilmedi'),esc(r.owner)+'<br>'+esc(r.submittedAt),esc(r.status),esc(r.reviewNote||'—')+'<br>'+esc(r.reviewer||''),'<span data-submission-docs="'+esc(r.id)+'"></span>',review&&r.status==='Onay bekliyor'?'<button data-review-invoice="'+esc(r.id)+'">İncele / onayla</button><button data-return-invoice="'+esc(r.id)+'">Düzeltmeye gönder</button>':r.status==='Düzeltme istendi'&&r.owner===user.name?'<button data-resubmit-invoice="'+esc(r.id)+'">Düzelt ve yeniden gönder</button>':'—']));$('#approval-new').onclick=()=>invoiceEntry();if(user.role==='field'){const back=document.createElement('button');back.textContent='Görevlerime dön';back.onclick=()=>go('today');$('#content').prepend(back);}document.querySelectorAll('[data-review-invoice]').forEach(b=>b.onclick=()=>invoiceEntry(false,find('invoiceSubmissions',b.dataset.reviewInvoice)));document.querySelectorAll('[data-resubmit-invoice]').forEach(b=>b.onclick=()=>invoiceEntry(false,find('invoiceSubmissions',b.dataset.resubmitInvoice)));document.querySelectorAll('[data-return-invoice]').forEach(b=>b.onclick=()=>form('Düzeltmeye gönder',[{key:'note',label:'Eksik / düzeltilecek bilgi'}],async x=>{if(demo){Object.assign(find('invoiceSubmissions',b.dataset.returnInvoice),{status:'Düzeltme istendi',reviewNote:x.note,reviewer:user.name});app();}else{await api('invoice-approval',{action:'return',id:b.dataset.returnInvoice,note:x.note});await load();}}));
 const show=docs=>{for(const r of rs){const el=document.querySelector('[data-submission-docs="'+r.id+'"]');if(el)el.innerHTML=docs.filter(d=>d.target==='invoiceSubmissions:'+r.id||r.expense&&d.target==='expenses:'+r.expense).map(d=>'<a href="/api/file/'+encodeURIComponent(d.id)+'">'+esc(d.name)+'</a>').join('<br>')||'Belge yok';}};if(user.role==='field')api('portal-documents').then(x=>show(x.rows)).catch(e=>notice(e.message));else show(rows('documents'));
}

const approvalExpenseEdit=edit;edit=function(k,r){if(k==='expenses'&&!r&&schema.invoiceSubmissions)return invoiceEntry();return approvalExpenseEdit(k,r);};
